### ISSUE TITLE
Program freezes while trying to refresh modlist

### ISSUE THREAD

**Issue by delatoid** [pukmajster/funky#10] opened 2024-07-30 05:10 UTC
I think this started happening after the July 26 update. I can still do everything else as normal, but refreshing the mod list just causes Funky to infinitely load and the program to eventually stop responding

**Comment by pukmajster** [comment] 2024-08-05 19:32
Refreshing still works for me, even after the update. Even then, I can't see why a small game update would break Funky. How many mods do you have installed? Can you also try refreshing after going into settings and disabling networking? 

Sadly, I don't have enough info yet to find the root cause of this.

**Comment by delatoid** [comment] 2024-08-08 12:52
I figured out the problem! It's the last paragraph but I left my process here just in case it helps:

I had 242 mods subscribed to before the problems started happening, and 251 afterwards.

I tried the following things to no avail:

- Refreshing with networking enabled and disabled
- Unsubscribing to the 9 mods I subscribed to after the update
- Validating file integrity
- Uninstalling + Reinstalling L4D2 and Funky
- Clearing out the appdata folder
- Changing which drive L4D2 is installed on

Changing to a different account seemed to work, so then I figured maybe it was a problem with a mod I had subscribed to.

[Figured out being subscribed to this mod was causing the issues](https://steamcommunity.com/sharedfiles/filedetails/?id=3141545792), which is strange because I unsubscribed to it earlier as well and Funky still had trouble refreshing. Otherwise, yeah everything works fine as long as I'm not subscribed to that mod.

**Comment by pukmajster** [comment] 2024-08-09 19:57
Thanks for going through the hassle, mate. I'll take a look at this pesky mod and see what goes wrong.

**Comment by pukmajster** [comment] 2024-09-16 23:53
Welp, the issue comes from calling `.toString('utf-8')` on the contents of the `addoninfo.txt` file!

Said file in question...

```
// 这个描述文件一定要用 Notepad++ 或其他文本软件去编辑（为了保持编码为 UTF-8无BOM），最好不要用系统自带记事本去编辑，否则编码容易变成ANSI，从而导致中文乱码！
// Notepad++ 请自行下载，其官网有严重国家反动内容，我个人拒绝提供。

"AddonInfo"	//
{  						//

     "addonSteamAppID"							"550"						// 游戏ID（无需修改）
     "addontitle"											"XDR Charger Animation(my asss!) v1.2"			// 标题
     "addonversion"										"1.2"						// 版本号
     "addontagline"										""								// 
     "addonauthor"										"热心网友"						// MOD作者
     "addonauthorSteamID"						""						// MOD作者的SteamID
     "addonContent_Campaign"				"0"							// 是否为地图MOD，1是0否
     "addonContent_Map"							"0"							// 是否为地图MOD
     "addonContent_Skin"							"0"							// 是否为皮肤MOD
     "addonContent_Weapon"					"0"							// 是否为武器MOD
     "addonContent_BossInfected"			"0"							// 是否为地图MOD
     "addonContent_CommonInfected"	"0"							// 是否为小僵尸MOD
     "addonContent_Survivor"					"0"							// 是否为生还者MOD
     "addonContent_Sound"						"0"							// 是否含有声音
     "addonContent_Script"						"0"							// 是否含有脚本
     "addonURL0"										""								// MOD发布链接（可写可不写）
     "addonDescription								"小心不要被牛牛抓到!--by热心网友。"								// MOD描述
	 
}						// ←别动
```

Honestly, at this point I'm ready to get rid of local addoninfo.txt parsing and rely fully on the API method, as these files have been nothing but pain to work with.

**Comment by pukmajster** [comment] 2024-10-14 17:11
I think I have a workaround for this issue, I'll get to it on wednesday!

**Comment by pukmajster** [comment] 2024-10-15 18:39
Alright, thanks for the help, mate. Can't wait to find the most malformed addoninfo.txt's imaginable hiding in those VPKs

**Comment by pukmajster** [comment] 2024-10-16 18:20
I adjusted how Funky gets the metadata for mods. All Workshop mods now get their data from the Workshop API directly, while the traditional method of reading the VPK's addoninfo.txt remains for mods installed outside of the Workshop.

While this is not a full fix, it will prevent any and all Workshop mods from crashing Funky. Expect the update tomorrow along with some other smaller goodies!

**Comment by pukmajster** [comment] 2024-10-16 23:53
The update is out! Check out the [latest release](https://github.com/pukmajster/funky/releases/tag/v0.3.1) and let me know if it's fixed for you.

**Comment by Necrilem** [comment] 2024-10-17 08:21
I tested again with the Axe skin I posted and it seems to have fixed it. No issues refreshing the list this time.

I know this isn't the right place but I don't know where else to ask so I'll do that here, sorry for that.

Do you think a feature is possible that converts workshop mods into manual mods? Basically moves them all up a folder and updates the paths. I have around 600 mods and every time I start the game, I need to wait like 10+ minutes for it to load all Add-Ons because it checks them against their workshop pages. Having them as manual mods supposedly completely removes this wait times but when I tried to move them manually, it broke them all in Funky (especially all the shuffle playlists).

**Comment by pukmajster** [comment] 2024-10-17 10:24
I'll be closing this specific issue since it's fixed.

**Closed by pukmajster** 2024-10-17 10:24 UTC
Labels: bug
